import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link"
import "./globals.css";
import GlobalState, { CartContext } from "@/context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen flex-col items-center p-24">
          <nav className="z-10 w-full max-w-5xl items-center justify-between text-sm lg:flex">
            <ul>
              <li>
                <Link href="/">Home</Link>
              </li>
              <li>
                <Link href="/list">Pokemons</Link>
              </li>
              <li>
                <Link href="/cart">Cart</Link>
              </li>
              <li>Nav x</li>
              <li>Nav y</li>
            </ul>
          </nav>
          <GlobalState>
            {children}
          </GlobalState>
        </main>
      </body>
    </html>
  );
}
