import Link from "next/link"
import "./globals.css";
import GlobalState from "@/context";
import { CartCounter } from "./components/cart-counter";

export const metadata = {
    title: "Next.js Poke Store",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <GlobalState>
                    <header>
                        <nav className="topnav">
                            <ul>
                                <li>
                                    <Link href="/">Pokemons</Link>
                                </li>
                                <li>
                                    <Link href="/cart">Cart: <CartCounter /></Link>
                                </li>
                            </ul>
                        </nav>
                    </header>
                    <div className="container">
                        {children}
                    </div>
                </GlobalState>
            </body>
        </html>
    );
}
